[package]
name = "fast-imt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
RuDDy = { git = "https://github.com/CrackedPoly/RuDDy.git", version = "0.2.0", features = ["default"] }
log = "0.4.20"
nom = "7"
indexmap = "2.2.5"
rug = "1.24.0"

[profile.dev]
overflow-checks = false

