[package]
name = "rapimt"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
# Remember to enable this for a great improvement
# opt-level = 3
overflow-checks = false

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bitvec = { version = "1" }
fxhash = { version = "0.2.1" }
indexmap = { version = "2.2.5" }
log = { version = "0.4.25" }
env_logger = { version = "0.11.6" }
nom = { version = "7" }
num_enum = { version = "0.7.3" }
RuDDy = { git = "https://github.com/CrackedPoly/RuDDy.git", features = [
  "default",
] }
serde = { version = "1.0", features = ["derive"] }

[dependencies]
rapimt_internal = { path = "crates/rapimt_internal" }
document-features = "0.2"

[features]
default = ["dip"]

## Support encoding 32-bit destination IPv4 addresses
dip = ["rapimt_internal/dip"]

## Support encoding 32-bit source IPv4 addresses
sip = ["rapimt_internal/sip"]

## Support encoding 16-bit destination port numbers
dport = ["rapimt_internal/dport"]

## Support encoding 16-bit source port numbers
sport = ["rapimt_internal/sport"]

## Support encoding 16-bit VLAN tags
tag = ["rapimt_internal/tag"]

## Support encoding 16-bit InfiniBand lid
lid = ["rapimt_internal/lid"]

[[bin]]
doc = false
name = "rimt"
path = "crates/rapimt_cli/src/bin/rimt.rs"
