[package]
name = "fast-imt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
RuDDy = { path = "../RuDDy", version = "0.2.0", features = ["default"] }
once_cell = "1.19.0"

[profile.dev]
overflow-checks = false

