[package]
name = "rapimt_io"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapimt_core = { path = "../rapimt_core" , version = "0.2.2" }
rapimt_im = { path = "../rapimt_im" , version = "0.2.2" }
fxhash = { workspace = true }
nom = { workspace = true }
indexmap = { workspace = true }
num_enum = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
log = { workspace = true }
funty = "2.0.0"
pest = "2"
pest_derive = "2"
derivative = "2.2.0"
csv = "1.3.1"
hex = { version = "0.4.3", features = ["serde"] }
lazy_static = "1.5.0"

[[example]]
name = "stanford"
path = "examples/stanford/stanford.rs"
