[package]
name = "rapimt_io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapimt_core = { path = "../rapimt_core" }
nom = "7"
indexmap = "2.2.5"
