[package]
name = "rapimt-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapimt-core = { path = "../core" }
nom = "7"
indexmap = "2.2.5"
